// Generated by gencpp from file nubot_common/object_info.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_OBJECT_INFO_H
#define NUBOT_COMMON_MESSAGE_OBJECT_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace nubot_common
{
template <class ContainerAllocator>
struct object_info_
{
  typedef object_info_<ContainerAllocator> Type;

  object_info_()
    : header()
    , ball_pos()
    , obs_pos()
    , ball_know(false)
    , obs_know(false)  {
    }
  object_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ball_pos(_alloc)
    , obs_pos(_alloc)
    , ball_know(false)
    , obs_know(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _ball_pos_type;
  _ball_pos_type ball_pos;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obs_pos_type;
  _obs_pos_type obs_pos;

   typedef uint8_t _ball_know_type;
  _ball_know_type ball_know;

   typedef uint8_t _obs_know_type;
  _obs_know_type obs_know;




  typedef boost::shared_ptr< ::nubot_common::object_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_common::object_info_<ContainerAllocator> const> ConstPtr;

}; // struct object_info_

typedef ::nubot_common::object_info_<std::allocator<void> > object_info;

typedef boost::shared_ptr< ::nubot_common::object_info > object_infoPtr;
typedef boost::shared_ptr< ::nubot_common::object_info const> object_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_common::object_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_common::object_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nubot_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'nubot_common': ['/home/ubuntu/libfreenect2-master/src/nubot_common/msgs'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::object_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::object_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::object_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::object_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::object_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::object_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_common::object_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "799347d7afb7b966d6574b6b5aa1c5a4";
  }

  static const char* value(const ::nubot_common::object_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x799347d7afb7b966ULL;
  static const uint64_t static_value2 = 0xd6574b6b5aa1c5a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_common::object_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_common/object_info";
  }

  static const char* value(const ::nubot_common::object_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_common::object_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point[] ball_pos\n\
geometry_msgs/Point[] obs_pos\n\
bool ball_know\n\
bool obs_know\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::nubot_common::object_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_common::object_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ball_pos);
      stream.next(m.obs_pos);
      stream.next(m.ball_know);
      stream.next(m.obs_know);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_common::object_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_common::object_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ball_pos[]" << std::endl;
    for (size_t i = 0; i < v.ball_pos.size(); ++i)
    {
      s << indent << "  ball_pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.ball_pos[i]);
    }
    s << indent << "obs_pos[]" << std::endl;
    for (size_t i = 0; i < v.obs_pos.size(); ++i)
    {
      s << indent << "  obs_pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obs_pos[i]);
    }
    s << indent << "ball_know: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ball_know);
    s << indent << "obs_know: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obs_know);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_OBJECT_INFO_H
