// Generated by gencpp from file nubot_common/ObstaclesInfo3d.msg
// DO NOT EDIT!


#ifndef NUBOT_COMMON_MESSAGE_OBSTACLESINFO3D_H
#define NUBOT_COMMON_MESSAGE_OBSTACLESINFO3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nubot_common/Point3d.h>
#include <nubot_common/Point3d.h>

namespace nubot_common
{
template <class ContainerAllocator>
struct ObstaclesInfo3d_
{
  typedef ObstaclesInfo3d_<ContainerAllocator> Type;

  ObstaclesInfo3d_()
    : header()
    , pos()
    , pos_min()
    , pos_known_3d(false)
    , pos_known_2d(false)  {
    }
  ObstaclesInfo3d_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)
    , pos_min(_alloc)
    , pos_known_3d(false)
    , pos_known_2d(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::nubot_common::Point3d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nubot_common::Point3d_<ContainerAllocator> >::other >  _pos_type;
  _pos_type pos;

   typedef  ::nubot_common::Point3d_<ContainerAllocator>  _pos_min_type;
  _pos_min_type pos_min;

   typedef uint8_t _pos_known_3d_type;
  _pos_known_3d_type pos_known_3d;

   typedef uint8_t _pos_known_2d_type;
  _pos_known_2d_type pos_known_2d;




  typedef boost::shared_ptr< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclesInfo3d_

typedef ::nubot_common::ObstaclesInfo3d_<std::allocator<void> > ObstaclesInfo3d;

typedef boost::shared_ptr< ::nubot_common::ObstaclesInfo3d > ObstaclesInfo3dPtr;
typedef boost::shared_ptr< ::nubot_common::ObstaclesInfo3d const> ObstaclesInfo3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nubot_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'nubot_common': ['/home/ubuntu/libfreenect2-master/src/nubot_common/msgs'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60241ee2c1942a7ff4999dfb0ac383c8";
  }

  static const char* value(const ::nubot_common::ObstaclesInfo3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60241ee2c1942a7fULL;
  static const uint64_t static_value2 = 0xf4999dfb0ac383c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nubot_common/ObstaclesInfo3d";
  }

  static const char* value(const ::nubot_common::ObstaclesInfo3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Point3d[]   pos\n\
Point3d     pos_min\n\
\n\
bool      pos_known_3d\n\
bool      pos_known_2d\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nubot_common/Point3d\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::nubot_common::ObstaclesInfo3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
      stream.next(m.pos_min);
      stream.next(m.pos_known_3d);
      stream.next(m.pos_known_2d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclesInfo3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nubot_common::ObstaclesInfo3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nubot_common::ObstaclesInfo3d_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nubot_common::Point3d_<ContainerAllocator> >::stream(s, indent + "    ", v.pos[i]);
    }
    s << indent << "pos_min: ";
    s << std::endl;
    Printer< ::nubot_common::Point3d_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_min);
    s << indent << "pos_known_3d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_known_3d);
    s << indent << "pos_known_2d: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_known_2d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NUBOT_COMMON_MESSAGE_OBSTACLESINFO3D_H
